version: '3.8'

services:
  neo4j:
    image: neo4j:5.15
    container_name: kg-neo4j
    ports:
      - "7474:7474"  # Neo4j Browser
      - "7687:7687"  # Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/test12345
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - kg-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kg-backend
    ports:
      - "8000:8000"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=test12345
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    depends_on:
      - neo4j
    networks:
      - kg-network
    restart: unless-stopped

  frontend:
    image: node:18-alpine
    container_name: kg-frontend
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    depends_on:
      - backend
    networks:
      - kg-network
    restart: unless-stopped

volumes:
  neo4j_data:
  neo4j_logs:

networks:
  kg-network:
    driver: bridge